use_frameworks!

target 'DVIA-v2' do
    pod 'Parse'
    pod 'GoogleAnalytics'
    pod 'RealmSwift'
    pod 'couchbase-lite-ios'
    pod 'Flurry-iOS-SDK/FlurrySDK'
end

# Combined post_install hook
post_install do |installer|
  # Fix for simulator arm64 issue (common with M1/M2/M3 Macs)
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end

  # Fix for libarclite / old deployment target error (Bolts, Realm, etc.)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 13.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end